# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.data_Table_Widget = QtWidgets.QTableWidget(self.centralwidget)
        self.data_Table_Widget.setGeometry(QtCore.QRect(60, 90, 611, 381))
        self.data_Table_Widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.data_Table_Widget.setDragEnabled(True)
        self.data_Table_Widget.setRowCount(0)
        self.data_Table_Widget.setColumnCount(0)
        self.data_Table_Widget.setObjectName("data_Table_Widget")
        self.graphSettings_Button = QtWidgets.QPushButton(self.centralwidget)
        self.graphSettings_Button.setGeometry(QtCore.QRect(280, 510, 111, 34))
        self.graphSettings_Button.setObjectName("graphSettings_Button")
        self.additional_Rows_SpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.additional_Rows_SpinBox.setGeometry(QtCore.QRect(190, 40, 52, 32))
        self.additional_Rows_SpinBox.setMaximum(100000)
        self.additional_Rows_SpinBox.setObjectName("additional_Rows_SpinBox")
        self.additional_Columns_SpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.additional_Columns_SpinBox.setGeometry(QtCore.QRect(410, 40, 52, 32))
        self.additional_Columns_SpinBox.setMaximum(1000)
        self.additional_Columns_SpinBox.setObjectName("additional_Columns_SpinBox")
        self.additional_Rows_Label = QtWidgets.QLabel(self.centralwidget)
        self.additional_Rows_Label.setGeometry(QtCore.QRect(70, 50, 101, 18))
        self.additional_Rows_Label.setObjectName("additional_Rows_Label")
        self.additional_Columns_Label = QtWidgets.QLabel(self.centralwidget)
        self.additional_Columns_Label.setGeometry(QtCore.QRect(270, 50, 121, 18))
        self.additional_Columns_Label.setObjectName("additional_Columns_Label")
        self.add_Rows_Columns_Button = QtWidgets.QPushButton(self.centralwidget)
        self.add_Rows_Columns_Button.setGeometry(QtCore.QRect(490, 40, 51, 34))
        self.add_Rows_Columns_Button.setObjectName("add_Rows_Columns_Button")
        self.delete_Rows_Columns_Button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_Rows_Columns_Button.setGeometry(QtCore.QRect(570, 40, 71, 34))
        self.delete_Rows_Columns_Button.setObjectName("delete_Rows_Columns_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 30))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionEnter_table = QtWidgets.QAction(MainWindow)
        self.actionEnter_table.setObjectName("actionEnter_table")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.actionSave_All = QtWidgets.QAction(MainWindow)
        self.actionSave_All.setObjectName("actionSave_All")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClose_all = QtWidgets.QAction(MainWindow)
        self.actionClose_all.setObjectName("actionClose_all")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionEnter_table)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_All)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionClose_all)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inferno"))
        self.graphSettings_Button.setText(_translate("MainWindow", "Graph settings"))
        self.additional_Rows_Label.setText(_translate("MainWindow", "Additional rows"))
        self.additional_Columns_Label.setText(_translate("MainWindow", "Additional columns"))
        self.add_Rows_Columns_Button.setText(_translate("MainWindow", "Add "))
        self.delete_Rows_Columns_Button.setText(_translate("MainWindow", "Delete"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&dit"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menuOptions.setTitle(_translate("MainWindow", "Optio&ns"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionOpen_file.setText(_translate("MainWindow", "&Open file"))
        self.actionEnter_table.setText(_translate("MainWindow", "&Enter table"))
        self.action_3.setText(_translate("MainWindow", "______________________"))
        self.actionSave_All.setText(_translate("MainWindow", "&Save All"))
        self.actionSave_as.setText(_translate("MainWindow", "Sa&ve as"))
        self.actionClose.setText(_translate("MainWindow", "&Close"))
        self.actionClose_all.setText(_translate("MainWindow", "C&lose all"))
        self.actionPrint.setText(_translate("MainWindow", "&Print"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionSettings.setText(_translate("MainWindow", "&Settings"))

