# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.data_Table_Widget = QtWidgets.QTableWidget(self.centralwidget)
        self.data_Table_Widget.setGeometry(QtCore.QRect(450, 80, 461, 361))
        self.data_Table_Widget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.data_Table_Widget.setDragEnabled(True)
        self.data_Table_Widget.setRowCount(0)
        self.data_Table_Widget.setColumnCount(0)
        self.data_Table_Widget.setObjectName("data_Table_Widget")
        self.path_To_File_Label = QtWidgets.QLabel(self.centralwidget)
        self.path_To_File_Label.setGeometry(QtCore.QRect(50, 440, 28, 18))
        self.path_To_File_Label.setObjectName("path_To_File_Label")
        self.browse_Button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_Button.setGeometry(QtCore.QRect(280, 460, 84, 31))
        self.browse_Button.setMouseTracking(True)
        self.browse_Button.setObjectName("browse_Button")
        self.name_Of_Sheet_Label = QtWidgets.QLabel(self.centralwidget)
        self.name_Of_Sheet_Label.setGeometry(QtCore.QRect(40, 520, 90, 18))
        self.name_Of_Sheet_Label.setObjectName("name_Of_Sheet_Label")
        self.cell_Range_Label = QtWidgets.QLabel(self.centralwidget)
        self.cell_Range_Label.setGeometry(QtCore.QRect(220, 520, 62, 18))
        self.cell_Range_Label.setObjectName("cell_Range_Label")
        self.name_Of_Sheet_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_Of_Sheet_LineEdit.setGeometry(QtCore.QRect(40, 540, 141, 32))
        self.name_Of_Sheet_LineEdit.setObjectName("name_Of_Sheet_LineEdit")
        self.cell_Range_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cell_Range_LineEdit.setGeometry(QtCore.QRect(220, 540, 141, 32))
        self.cell_Range_LineEdit.setObjectName("cell_Range_LineEdit")
        self.path_To_File_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.path_To_File_lineEdit.setGeometry(QtCore.QRect(40, 460, 221, 32))
        self.path_To_File_lineEdit.setObjectName("path_To_File_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 30))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionEnter_table = QtWidgets.QAction(MainWindow)
        self.actionEnter_table.setObjectName("actionEnter_table")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.actionSave_All = QtWidgets.QAction(MainWindow)
        self.actionSave_All.setObjectName("actionSave_All")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionClose_all = QtWidgets.QAction(MainWindow)
        self.actionClose_all.setObjectName("actionClose_all")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionEnter_table)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_All)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionClose_all)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inferno"))
        self.path_To_File_Label.setText(_translate("MainWindow", "Path"))
        self.browse_Button.setText(_translate("MainWindow", "Browse..."))
        self.name_Of_Sheet_Label.setText(_translate("MainWindow", "Name of sheet"))
        self.cell_Range_Label.setText(_translate("MainWindow", "Cell range"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&dit"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuOptions.setTitle(_translate("MainWindow", "Optio&ns"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionEnter_table.setText(_translate("MainWindow", "Enter table"))
        self.action_3.setText(_translate("MainWindow", "______________________"))
        self.actionSave_All.setText(_translate("MainWindow", "Save All"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose_all.setText(_translate("MainWindow", "Close all"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

